version: "3.9"

services:
  prescription:
    build: ./Model           # bug thi ong thay bang image: xuanbao01/prescription nhu hien tai nhe
    ports:
      - "8000:8000"
    working_dir: /app/Model
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app 

  chatbot:
    image: xuanbao01/chatbot
    ports:
      - "8001:8001"
    command: uvicorn main:app --host 0.0.0.0 --port 8001 --reload