version: "3.9"

services:
  prescription:
    build: ./Model
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./images:/app/images # Ánh xạ file test.py từ máy vào container